[package]
name = "rpg"
version = "0.1.0"
authors = ["David Ayeke"]

[dependencies]
ggez = "0.4"
derivative = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiled = "0.8.0"

[lib]
name = "rpg"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"